### ISSUE TITLE
YAML output helper function

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#32]
## Expected Behavior
I can create a generated document which is treated like a JSON/freemarker object syntax during template generation but converted to yaml on export

## Current Behavior
JSON support only

## Possible Solution
Add a helper function to the freemarker wrapper which will convert from JSON to YAML. This function can be executed by freemarker when creating a file. This could follow on from the work in #23 

## Context
Some tools ( Jenkins config as code ) only supports YAML based files for its definitions. In order to dynamically create some sections of the configuraton for a Jenkins master we need a way to generate a yaml file

**Comment by ml019** [comment]
I'd suggest we add an ``outputSerialisation" input parameter that can be used directly in the toCMDB() function as well as handled by the wrapper itself. Valid values "json", "yml" and "yaml"

Over time I think it will be the toCMDB() function that will do most writing as knowledge of the cmdb structure moves increasingly into the engine. In the interim, the wrapper can examine the output from freemarker and if it looks like JSON, switch it to YAML depending on the value of the input parameter.

**Comment by roleyfoley** [comment]
@kshychko has this been implemented in the wrapper yet? I know we have some yaml input conversion just wasn't sure if the output was included

**Comment by ml019** [comment]
@kshychko - I think we have implemented this in toCMDB() so the ticket can be closed? With the work @roleyfoley has been doing with multiple outputs, I think a single outputSerialisation parameter needs to be replaced with one per output to be generated. This can be handled via a separate ticket as it isn't relevant to the wrapper.

**Comment by roleyfoley** [comment]
@roleyfoley will test this out with the new output writer

**Comment by roleyfoley** [comment]
Confirmed that this is working and it has now been added into the engine support
