### ISSUE TITLE
bug: multiple plugin handling in mingw

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine-core#38]
## Expected Behaviour
It should be possible to include multiple, semi-colon separated plugin dirs in `GENERATION_PLUGIN_DIRS`.

## Current Behaviour
The wrapper reports the first plugin as not present and ignores the remainder.

## Steps to Reproduce (for bugs)
1. `export GENERATION_PLUGIN_DIRS="/c/repos/hamlet/engine-plugin-aws;/c/repos/hamlet/engine-plugin-cmdb"`
2. run create template
3. `Exception in thread "main" java.io.FileNotFoundException: \c\repos\hamlet\engine-plugin-aws does not exist.`

## Context
Developing new plugin under mingw

**Comment by roleyfoley** [comment]
You can include multiple directories on the list but they currently have to end in a trailing slash.
I guess a directory technically is the slash at the end so not sure if that's an issue or not

**Comment by ml019** [comment]
@roleyfoley one works without a slash for me. @kshychko would you mind ensuring trailing slash/no trailing slash  is handled correctly

**Comment by ml019** [comment]
@kshychko think this was fixed in 1.12.1? If so, please close.

**Comment by kshychko** [comment]
@ml019 , yes, it was.
