### ISSUE TITLE
Add Github release support for the freemarker wrapper build

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#39]
## Expected Behaviour
Builds of the freemarker wrapper are built and available from the releases section of this repository

## Current Behaviour
Builds are created by the developer who creates the change and are included in the repo as binary blobs

## Possible Solution
Add a Java build process as a github action which supports publishing releases to this repository. Builds and tests should run on all builds but releases are created on repo tags

## Context
This would allow for us to automate the build and test of the freemarker wrapper inline with CI/CD convetions

**Comment by ml019** [comment]
@kshychko shal we all this before the next rc release?

**Comment by kshychko** [comment]
@ml019, I raised a PR #40

**Comment by kshychko** [comment]
I added a tag to v1.11.1 (current version in master) to test the workflows, so you can check out releases:
https://github.com/hamlet-io/engine-core/releases

**Comment by RossMurr4y** [comment]
@roleyfoley I think we're good to close this one now?

Do we have any need to build/publish previous versions of the wrapper?

**Comment by roleyfoley** [comment]
Not that I can think of. Thanks @kshychko for adding this in
