### ISSUE TITLE
feat: Files/Directories only search optimisation

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine-core#42]
## Expected Behaviour
It should be possible to request directories only or files only when querying the cmdb

## Current Behaviour
Currently this can only be done post search by checking the "IsDirectory"  attribute. IT would be more efficient to perform this filtering pre regex checking.

## Possible Solution
- Add `IgnoreDirectories` option to `getCMDBTree()` with a default of false which will not include directories when scanning the file system
- Add `IgnoreFiles` option to `getCMDBTree()` with a default of false which will not include files when scanning the file system

## Context
Searching for directories only is used when determining the cmdb structure. Searching for files only is common when analysing the files within the top level directories of the cmdb structure.

## Your Environment

* CMDB Version used: 
* Blueprint:

**Comment by ml019** [comment]
@kshychko please close once production tag is built

**Comment by kshychko** [comment]
a release has been created for v1.12.3 tag
