### ISSUE TITLE
Custom exceptions and return codes

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#44]
## Expected Behaviour
Exceptions generated by the engine are standardised and handled by the engine itself. 

## Current Behaviour
Error messages in the engine are currently classified by the executor once the exception is thrown by the engine

## Possible Solution
Is it possible to create new exception freemarker method which allows for the setting the exit code, status code and along with an exception method. Currently the only exception method available is the freemarker builtin stop method, which only allows for string returns

## Context
With https://github.com/hamlet-io/executor-bash/pull/168 and https://github.com/hamlet-io/architectural-decision-log/pull/5 we've identified the need for more complex error handling across hamlet in general. The current implementation relies on the executor to classify messages generated by the engine.

**Comment by ml019** [comment]
Agreement is to 
- add a `setExitStatus()` function to the wrapper which will accept the non-negative status that the wrapper should return on exit. If called multiple times, the last value will be returned. IF not called at all, 0 should be returned.

Exit status 100-109 are reserved for the engine to capture freemarker exceptions and return the results. 100 will be used for an caught (stop) exception and 101 for an uncaught one. So basically take the logic for this currently in executor-bash and move into the wrapper. This logic will rely on exceptions thrown by the freemarker engine and caught inside the wrapper where the engine is invoked.

**Comment by kshychko** [comment]
The code has been refactored, additional exceptions were introduced:

- 100 - stop exception
- 101 - template exception
- 102 - uncaught exception
- 200 - IO exception
- 201 - cli exception
- 202 - number of arguments exception
- 203 - parameter value exception
- 204 - clone not supported exception (cpCMDB and toCMDB)
- 209 - general wrapper exception

Syntax:
```
[#local status = 150]
[#local result = setExitStatus(status)]
```
Allowed values for `status` - 110-199 and 210-254.

**Comment by roleyfoley** [comment]
Confirmed that exit codes are being set properly and that the engine can set the codes as it needs to.
