### ISSUE TITLE
stdout and stderr functions for freemarker wrapper

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#45]
## Expected Behaviour

A function can be called from within the freemarker engine to write output either the stdout or stderr console pipes. 

## Current Behaviour

We currently rely on output files generated by the engine to provide feedback to users and the bash executor reads the output file and then sends sections of it to stdout and stderr

## Possible Solution

Add functions to the freemarker wrapper similar to the toCMDB function which will right to the console 

## Context

With the move to using the toCMDB function when a process fails within the engine that generates a fatal message or there is an issue with writing an output we won't be able to see the output or find results

**Comment by roleyfoley** [comment]
@kshychko Could you please investigate this 

function name something like toConsole? Probably need to see what is available to see what options we need

**Comment by kshychko** [comment]
@roleyfoley , I rased a PR #50 

The syntax is similar to toCMDB:
```
[#local result =
  toConsole(
    content,
    {
      "SendTo" : "stdout|stderr"
    }
  ) ]
````

The default value for SendTo is stdout, can be changed if needed.

**Comment by roleyfoley** [comment]
Tested and confirmed working in https://github.com/hamlet-io/engine/pull/1639
