### ISSUE TITLE
JSON Output formatting

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#46]
## Expected Behaviour

When using toCMDB I can specify if a JSON file should be pretty formatted or compressed 

## Current Behaviour

All file outputs are compressed JSON files on a single line

## Possible Solution

Add an option to specify Formatted on the toCMDB option. When this is specified the JSON output will be formatted with each key on a new line with 2 space indenting. Similar to the JQ standard output 

```bash 
echo '{ "this" : {"that": "other"}}' | jq 
```

```json
{
  "this": {
    "that": "other"
  }
}
```

## Context

This helps with debugging and readability of the output provided by the engine

**Comment by kshychko** [comment]
@ml019 , would you like to pick a name for a new parameter of toCMDB method?

**Comment by ml019** [comment]
@kshychko Suggest two options 

Formatting: pretty or compressed (default)
Indent: 2 (default)

Indent only relevant for pretty formatting

**Comment by ml019** [comment]
Changes merged.
