### ISSUE TITLE
Hide stack trace on stop exception

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-core#53]
## Expected Behaviour

When a stop exception is raised within templates the stop reason is logged but the stack trace isn't included

## Current Behaviour

When a stop event is raised the full stack trace is included in the log 

## Possible Solution

When handling the stop exception only log the message provided if possible and don't include the stack trace log to the console

## Context

The stop method is used to stop processing at a user level and our convention is mostly to use the stop event as part of a fatal log message. This means the stack trace won't really provide information that is useful in debugging an issue

**Comment by kshychko** [comment]
@roleyfoley, could you please confirm the implentation is working as expected?
