### ISSUE TITLE
[BUG] Appending to a non-existent file throws a Java exception

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine-core#62]
## Current Behaviour
If appending to a non-existent file, an exception is thrown.

## Expected Behaviour
It would be preferrable if this followed shell redirection semantics and created the file is it doesn't exist.

## Possible Solution
Fix underlying Java calls

## Steps to Reproduce

1. Call `toCMDB` with `Append : true` as an option for a non-existent file

**Comment by kshychko** [comment]
@ml019, I fixed the bug in #63. Please note that a destination directory still need to exist, only a file is created if it doesn't exist.

**Comment by ml019** [comment]
Yep - that sounds fine
