### ISSUE TITLE
[BUG] Lambda unit template generation failure

### ISSUE THREAD

**Issue by kshychko** [hamlet-io/engine-core#79]
## Current Behaviour

Template generation is failing for lambda components with the following error:
22:08:54  FreeMarker template error:
22:08:54  For "?eval" left-hand operand: Expected a string or something automatically convertible to string (number, date or boolean), but this has evaluated to an extended_hash (wrapper: f.c.AddConcatExpression$ConcatenatedHashEx):
22:08:54  ==> settings  [in template "shared/inputseeders/shared/id.ftl" at line 374, column 64]
22:08:54  
22:08:54  ----
22:08:54  FTL stack trace ("~" means nesting-related):
22:08:54  	- Failed at: #local compositeSettings = (settings!...  [in template "shared/inputseeders/shared/id.ftl" in function "shared_configseeder_cmdb" at line 374, column 5]
22:08:54  	- Reached through: @internalRefreshInputState  [in template "inputdata/inputsource.ftl" in function "getInputState" at line 448, column 9]
22:08:54  	- Reached through: @writeStarterMessage writers=getComma...  [in template "invokeEntrance.ftl" in function "invokeEntrancePass" at line 101, column 5]
22:08:54  ----
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment
* CMDB Version used: v2.0.1
* Blueprint:

**Comment by roleyfoley** [comment]
@kshychko Does the lambda have an fragment where a variable called settings is assigned? 

If it does then I'd suggest change the variable name from settings to something else. Now that we are running multiple passes across the templates using the settings as a global variable replaces the initial settings variable and causes this to fail.

**Comment by kshychko** [comment]
@roleyfoley , I fixed the fragment files and it helped. Thanks for the hint!
